// Code generated by https://github.com/src-d/go-kallax. DO NOT EDIT.
// Please, do not touch the code below, and if you do, do it under your own
// risk. Take into account that all the code you write here will be completely
// erased from earth the next time you generate the kallax models.
package models

import (
	"database/sql"
	"fmt"
	"time"

	"gopkg.in/src-d/go-kallax.v1"
	"gopkg.in/src-d/go-kallax.v1/types"
)

var _ types.SQLType
var _ fmt.Formatter

type modelSaveFunc func(*kallax.Store) error

// NewABC returns a new instance of ABC.
func NewABC(name string) (record *ABC) {
	return newABC(name)
}

// GetID returns the primary key of the model.
func (r *ABC) GetID() kallax.Identifier {
	return (*kallax.NumericID)(&r.ID)
}

// ColumnAddress returns the pointer to the value of the given column.
func (r *ABC) ColumnAddress(col string) (interface{}, error) {
	switch col {
	case "id":
		return (*kallax.NumericID)(&r.ID), nil
	case "created_at":
		return &r.Timestamps.CreatedAt, nil
	case "updated_at":
		return &r.Timestamps.UpdatedAt, nil
	case "name":
		return &r.Name, nil

	default:
		return nil, fmt.Errorf("kallax: invalid column in ABC: %s", col)
	}
}

// Value returns the value of the given column.
func (r *ABC) Value(col string) (interface{}, error) {
	switch col {
	case "id":
		return r.ID, nil
	case "created_at":
		return r.Timestamps.CreatedAt, nil
	case "updated_at":
		return r.Timestamps.UpdatedAt, nil
	case "name":
		return r.Name, nil

	default:
		return nil, fmt.Errorf("kallax: invalid column in ABC: %s", col)
	}
}

// NewRelationshipRecord returns a new record for the relatiobship in the given
// field.
func (r *ABC) NewRelationshipRecord(field string) (kallax.Record, error) {
	return nil, fmt.Errorf("kallax: model ABC has no relationships")
}

// SetRelationship sets the given relationship in the given field.
func (r *ABC) SetRelationship(field string, rel interface{}) error {
	return fmt.Errorf("kallax: model ABC has no relationships")
}

// ABCStore is the entity to access the records of the type ABC
// in the database.
type ABCStore struct {
	*kallax.Store
}

// NewABCStore creates a new instance of ABCStore
// using a SQL database.
func NewABCStore(db *sql.DB) *ABCStore {
	return &ABCStore{kallax.NewStore(db)}
}

// GenericStore returns the generic store of this store.
func (s *ABCStore) GenericStore() *kallax.Store {
	return s.Store
}

// SetGenericStore changes the generic store of this store.
func (s *ABCStore) SetGenericStore(store *kallax.Store) {
	s.Store = store
}

// Debug returns a new store that will print all SQL statements to stdout using
// the log.Printf function.
func (s *ABCStore) Debug() *ABCStore {
	return &ABCStore{s.Store.Debug()}
}

// DebugWith returns a new store that will print all SQL statements using the
// given logger function.
func (s *ABCStore) DebugWith(logger kallax.LoggerFunc) *ABCStore {
	return &ABCStore{s.Store.DebugWith(logger)}
}

// DisableCacher turns off prepared statements, which can be useful in some scenarios.
func (s *ABCStore) DisableCacher() *ABCStore {
	return &ABCStore{s.Store.DisableCacher()}
}

// Insert inserts a ABC in the database. A non-persisted object is
// required for this operation.
func (s *ABCStore) Insert(record *ABC) error {
	record.SetSaving(true)
	defer record.SetSaving(false)

	record.CreatedAt = record.CreatedAt.Truncate(time.Microsecond)
	record.UpdatedAt = record.UpdatedAt.Truncate(time.Microsecond)

	if err := record.BeforeSave(); err != nil {
		return err
	}

	return s.Store.Insert(Schema.ABC.BaseSchema, record)
}

// Update updates the given record on the database. If the columns are given,
// only these columns will be updated. Otherwise all of them will be.
// Be very careful with this, as you will have a potentially different object
// in memory but not on the database.
// Only writable records can be updated. Writable objects are those that have
// been just inserted or retrieved using a query with no custom select fields.
func (s *ABCStore) Update(record *ABC, cols ...kallax.SchemaField) (updated int64, err error) {
	record.CreatedAt = record.CreatedAt.Truncate(time.Microsecond)
	record.UpdatedAt = record.UpdatedAt.Truncate(time.Microsecond)

	record.SetSaving(true)
	defer record.SetSaving(false)

	if err := record.BeforeSave(); err != nil {
		return 0, err
	}

	return s.Store.Update(Schema.ABC.BaseSchema, record, cols...)
}

// Save inserts the object if the record is not persisted, otherwise it updates
// it. Same rules of Update and Insert apply depending on the case.
func (s *ABCStore) Save(record *ABC) (updated bool, err error) {
	if !record.IsPersisted() {
		return false, s.Insert(record)
	}

	rowsUpdated, err := s.Update(record)
	if err != nil {
		return false, err
	}

	return rowsUpdated > 0, nil
}

// Delete removes the given record from the database.
func (s *ABCStore) Delete(record *ABC) error {
	return s.Store.Delete(Schema.ABC.BaseSchema, record)
}

// Find returns the set of results for the given query.
func (s *ABCStore) Find(q *ABCQuery) (*ABCResultSet, error) {
	rs, err := s.Store.Find(q)
	if err != nil {
		return nil, err
	}

	return NewABCResultSet(rs), nil
}

// MustFind returns the set of results for the given query, but panics if there
// is any error.
func (s *ABCStore) MustFind(q *ABCQuery) *ABCResultSet {
	return NewABCResultSet(s.Store.MustFind(q))
}

// Count returns the number of rows that would be retrieved with the given
// query.
func (s *ABCStore) Count(q *ABCQuery) (int64, error) {
	return s.Store.Count(q)
}

// MustCount returns the number of rows that would be retrieved with the given
// query, but panics if there is an error.
func (s *ABCStore) MustCount(q *ABCQuery) int64 {
	return s.Store.MustCount(q)
}

// FindOne returns the first row returned by the given query.
// `ErrNotFound` is returned if there are no results.
func (s *ABCStore) FindOne(q *ABCQuery) (*ABC, error) {
	q.Limit(1)
	q.Offset(0)
	rs, err := s.Find(q)
	if err != nil {
		return nil, err
	}

	if !rs.Next() {
		return nil, kallax.ErrNotFound
	}

	record, err := rs.Get()
	if err != nil {
		return nil, err
	}

	if err := rs.Close(); err != nil {
		return nil, err
	}

	return record, nil
}

// FindAll returns a list of all the rows returned by the given query.
func (s *ABCStore) FindAll(q *ABCQuery) ([]*ABC, error) {
	rs, err := s.Find(q)
	if err != nil {
		return nil, err
	}

	return rs.All()
}

// MustFindOne returns the first row retrieved by the given query. It panics
// if there is an error or if there are no rows.
func (s *ABCStore) MustFindOne(q *ABCQuery) *ABC {
	record, err := s.FindOne(q)
	if err != nil {
		panic(err)
	}
	return record
}

// Reload refreshes the ABC with the data in the database and
// makes it writable.
func (s *ABCStore) Reload(record *ABC) error {
	return s.Store.Reload(Schema.ABC.BaseSchema, record)
}

// Transaction executes the given callback in a transaction and rollbacks if
// an error is returned.
// The transaction is only open in the store passed as a parameter to the
// callback.
func (s *ABCStore) Transaction(callback func(*ABCStore) error) error {
	if callback == nil {
		return kallax.ErrInvalidTxCallback
	}

	return s.Store.Transaction(func(store *kallax.Store) error {
		return callback(&ABCStore{store})
	})
}

// ABCQuery is the object used to create queries for the ABC
// entity.
type ABCQuery struct {
	*kallax.BaseQuery
}

// NewABCQuery returns a new instance of ABCQuery.
func NewABCQuery() *ABCQuery {
	return &ABCQuery{
		BaseQuery: kallax.NewBaseQuery(Schema.ABC.BaseSchema),
	}
}

// Select adds columns to select in the query.
func (q *ABCQuery) Select(columns ...kallax.SchemaField) *ABCQuery {
	if len(columns) == 0 {
		return q
	}
	q.BaseQuery.Select(columns...)
	return q
}

// SelectNot excludes columns from being selected in the query.
func (q *ABCQuery) SelectNot(columns ...kallax.SchemaField) *ABCQuery {
	q.BaseQuery.SelectNot(columns...)
	return q
}

// Copy returns a new identical copy of the query. Remember queries are mutable
// so make a copy any time you need to reuse them.
func (q *ABCQuery) Copy() *ABCQuery {
	return &ABCQuery{
		BaseQuery: q.BaseQuery.Copy(),
	}
}

// Order adds order clauses to the query for the given columns.
func (q *ABCQuery) Order(cols ...kallax.ColumnOrder) *ABCQuery {
	q.BaseQuery.Order(cols...)
	return q
}

// BatchSize sets the number of items to fetch per batch when there are 1:N
// relationships selected in the query.
func (q *ABCQuery) BatchSize(size uint64) *ABCQuery {
	q.BaseQuery.BatchSize(size)
	return q
}

// Limit sets the max number of items to retrieve.
func (q *ABCQuery) Limit(n uint64) *ABCQuery {
	q.BaseQuery.Limit(n)
	return q
}

// Offset sets the number of items to skip from the result set of items.
func (q *ABCQuery) Offset(n uint64) *ABCQuery {
	q.BaseQuery.Offset(n)
	return q
}

// Where adds a condition to the query. All conditions added are concatenated
// using a logical AND.
func (q *ABCQuery) Where(cond kallax.Condition) *ABCQuery {
	q.BaseQuery.Where(cond)
	return q
}

// FindByID adds a new filter to the query that will require that
// the ID property is equal to one of the passed values; if no passed values,
// it will do nothing.
func (q *ABCQuery) FindByID(v ...int64) *ABCQuery {
	if len(v) == 0 {
		return q
	}
	values := make([]interface{}, len(v))
	for i, val := range v {
		values[i] = val
	}
	return q.Where(kallax.In(Schema.ABC.ID, values...))
}

// FindByCreatedAt adds a new filter to the query that will require that
// the CreatedAt property is equal to the passed value.
func (q *ABCQuery) FindByCreatedAt(cond kallax.ScalarCond, v time.Time) *ABCQuery {
	return q.Where(cond(Schema.ABC.CreatedAt, v))
}

// FindByUpdatedAt adds a new filter to the query that will require that
// the UpdatedAt property is equal to the passed value.
func (q *ABCQuery) FindByUpdatedAt(cond kallax.ScalarCond, v time.Time) *ABCQuery {
	return q.Where(cond(Schema.ABC.UpdatedAt, v))
}

// FindByName adds a new filter to the query that will require that
// the Name property is equal to the passed value.
func (q *ABCQuery) FindByName(v string) *ABCQuery {
	return q.Where(kallax.Eq(Schema.ABC.Name, v))
}

// ABCResultSet is the set of results returned by a query to the
// database.
type ABCResultSet struct {
	ResultSet kallax.ResultSet
	last      *ABC
	lastErr   error
}

// NewABCResultSet creates a new result set for rows of the type
// ABC.
func NewABCResultSet(rs kallax.ResultSet) *ABCResultSet {
	return &ABCResultSet{ResultSet: rs}
}

// Next fetches the next item in the result set and returns true if there is
// a next item.
// The result set is closed automatically when there are no more items.
func (rs *ABCResultSet) Next() bool {
	if !rs.ResultSet.Next() {
		rs.lastErr = rs.ResultSet.Close()
		rs.last = nil
		return false
	}

	var record kallax.Record
	record, rs.lastErr = rs.ResultSet.Get(Schema.ABC.BaseSchema)
	if rs.lastErr != nil {
		rs.last = nil
	} else {
		var ok bool
		rs.last, ok = record.(*ABC)
		if !ok {
			rs.lastErr = fmt.Errorf("kallax: unable to convert record to *ABC")
			rs.last = nil
		}
	}

	return true
}

// Get retrieves the last fetched item from the result set and the last error.
func (rs *ABCResultSet) Get() (*ABC, error) {
	return rs.last, rs.lastErr
}

// ForEach iterates over the complete result set passing every record found to
// the given callback. It is possible to stop the iteration by returning
// `kallax.ErrStop` in the callback.
// Result set is always closed at the end.
func (rs *ABCResultSet) ForEach(fn func(*ABC) error) error {
	for rs.Next() {
		record, err := rs.Get()
		if err != nil {
			return err
		}

		if err := fn(record); err != nil {
			if err == kallax.ErrStop {
				return rs.Close()
			}

			return err
		}
	}
	return nil
}

// All returns all records on the result set and closes the result set.
func (rs *ABCResultSet) All() ([]*ABC, error) {
	var result []*ABC
	for rs.Next() {
		record, err := rs.Get()
		if err != nil {
			return nil, err
		}
		result = append(result, record)
	}
	return result, nil
}

// One returns the first record on the result set and closes the result set.
func (rs *ABCResultSet) One() (*ABC, error) {
	if !rs.Next() {
		return nil, kallax.ErrNotFound
	}

	record, err := rs.Get()
	if err != nil {
		return nil, err
	}

	if err := rs.Close(); err != nil {
		return nil, err
	}

	return record, nil
}

// Err returns the last error occurred.
func (rs *ABCResultSet) Err() error {
	return rs.lastErr
}

// Close closes the result set.
func (rs *ABCResultSet) Close() error {
	return rs.ResultSet.Close()
}

type schema struct {
	ABC *schemaABC
}

type schemaABC struct {
	*kallax.BaseSchema
	ID        kallax.SchemaField
	CreatedAt kallax.SchemaField
	UpdatedAt kallax.SchemaField
	Name      kallax.SchemaField
}

var Schema = &schema{
	ABC: &schemaABC{
		BaseSchema: kallax.NewBaseSchema(
			"a",
			"__abc",
			kallax.NewSchemaField("id"),
			kallax.ForeignKeys{},
			func() kallax.Record {
				return new(ABC)
			},
			true,
			kallax.NewSchemaField("id"),
			kallax.NewSchemaField("created_at"),
			kallax.NewSchemaField("updated_at"),
			kallax.NewSchemaField("name"),
		),
		ID:        kallax.NewSchemaField("id"),
		CreatedAt: kallax.NewSchemaField("created_at"),
		UpdatedAt: kallax.NewSchemaField("updated_at"),
		Name:      kallax.NewSchemaField("name"),
	},
}
